### ISSUE TITLE
Automate workflow build

### ISSUE THREAD

**Issue by iguatemigarin** [xuyecan/alfred-chathub#2]
Hey, thank you for the great workflow.

What do you think about automating the build process?

**Comment by xuyecan** [comment]
Indeed, it should be improved. Do you have any suggestions? Since this workflow has not yet been published to the official gallery, I am afraid what I can do for now is write a script to package the files into a zip.

**Comment by xuyecan** [comment]
I’ll check out some other popular workflows and see what I can do.

**Comment by iguatemigarin** [comment]
Yes, should be just about zipping stuff. I checked the marketplace the other day and there seems to be a handful of actions there. I'll give it a shot maybe this weekend also and report back.

**Comment by iguatemigarin** [comment]
The thing is so simple that I just wrote the workflow, there is no need to use something external for now.

Let me know what you think: https://github.com/xuyecan/alfred-chathub/pull/3
